---
title: "CBP Data Codebook"
date: 09/29/2026
date-modified: 09/29/2026
author:
  - name: Graeme Blair
    url: https://graemeblair.com
    affiliation: University of California--Los Angeles
  - name: Simone Horowitz
    affiliation: University of California--Los Angeles
toc: false
freeze: false
---

:::: grid
::: {.g-col-12 .g-col-md-4 .g-col-lg-4}
### {{< bi archive class="me-2" >}} Documents

Agency documentation of CBP datasets.

[Explore](/docs/cbp/documents.html){.btn-action-primary .btn-action .btn .btn-outline-primary .btn-sm role="button"}
:::
::::

------------------------------------------------------------------------

We provide two Customs and Border Protection datasets on USBP encounters and USBP apprehensions. Separate, inconsistent files published at different times on CBP’s website under Freedom of Information Act statistical records are presented here in a single, usable dataset.

Under Title 8, an apprehension refers to those under physical control or temporary detainment by the United States Border Patrol (USBP) between Ports of Entry (POE) who are not lawfully in the United States, which may or may not result in an arrest.

Generally, encounters is an umbrella term refering to anyone apprehended by USBP under Title 8 Apprehensions, encountered by the OFO under Title 8 Inadmissibles, or expelled under Title 42 Expulsions. Due to a lack of published data, in this dataset, encounters refers specifically to USBP encounters, which include only Title 8 apprehensions and Title 42 expulsions and do not contain Title 8 inadmissibles.

During the COVID-19 pandemic, the Centers for Disease Control and Prevention (CDC) issued an order under Title 42 that permitted expedited expulsions at and between ports of entry from March 2020 through May 11, 2023. After May 11, 2023, enforcement reverted to Title 8 Apprehensions and Inadmissibles. Title 42 Expulsions are tracked separately from immigration enforcement actions.

## Data Structure

Each row represents one recorded CBP encounter involving an individual. Some records contain fields indicating whether multiple individuals were encountered together. The datasets are maintained separately because they represent different enforcement categories, CBP components, and source files. Variant column names are merged under standardized headers that are used across all three datasets.

## Data Processing

Files are identified by their URLs published on CBP’s website. As of now, if CBP replaces the contents of an existing URL the pipeline will not automatically detect this revision. We collected CBP data in these steps:

-   **Download apprehensions, inadmissibles, and encounters.** We identified and downloaded all relevant raw files from CBP’s original website. Any ambiguous files were manually reviewed.

-   **Profile header rows.** We examined the column names from each sheet to eventually build a crosswalk matching distinct column names to canonical counterparts.

-   **Build a crosswalk of canonical column names.** We created a crosswalk from the distinct columns identified in the previous step to assign each a canonical column name. Variant column names that contained the same expected entries were condensed.

-   **Convert original files to cleaned format.** We converted the headers in each dataset to their canonical name assigned in the crosswalk, ensuring that headers across all sheets were standardized.

-   **Identify dataset overlaps.** We extracted the minimum and maximum encounter dates in each cleaned file, exploring whether duplicate datasets existed. Datasets with the same minimum and maximum date and equal row counts were flagged and manually examined.

-   **Stack unique datasets.** Unique datasets were stacked to yield our first draft of apprehensions and encounters datasets. If files were determined to be erroneous duplicates, the faulty sheet was removed from parts to stack.

-   **Build code maps.** We created lookup tables to translate coded values into readable values, as well as cleaned versions of same-name variants.

-   **Clean combined datasets.** Finally, combined datasets were cleaned to standardize redaction codes and whitespace, convert columns to appropriate data types, order fields, and match values to their assignments in the code map.

-   **Resolve apprehension overlaps.** In the apprehensions dataset, several files were contained in files with broader date ranges. We identified more granular datasets and removed them from the final dataset to prevent duplicate records. This step was not performed in the encounters dataset, as no files had overlapping dates.

-   **Audit datasets.** We ran several audits to further investigate column missingness and preservation across processing steps.

-   **Cross reference with CBP dashboards.** We cross referenced monthly apprehension and encounter counts with monthly counts published on CBP dashboards.

-   **Final column selection.** Finally, we selected final columns based on missingness levels obtained from our audit step. Both the final datasets with selected columns and full final datasets are available. Several columns in the full final datasets are entirely or nearly all redacted or missing.

**Future work:** We are continuing to expand our datasets by submitting FOIA requests to obtain more recent datasets. We will update this codebook as processes develop.

## Data Sources

We list and link each of our data sources here.

| Name | Source | Date(s) in FY |
|------------------------|------------------------|------------------------|
| [CBP Apprehensions Data](https://www.cbp.gov/document/foia-record/customs-and-border-protection-border-patrol-statistics) | CBP, USBP | 2008–2026 |
| [CBP Encounters Data](https://www.cbp.gov/document/foia-record/customs-and-border-protection-border-patrol-statistics) | CBP | 2010–2025 |
| CBP Apprehensions PDFs |  | 2014 |

## Inspect Code

| Dataset | Code |
|------------------------------------|------------------------------------|
| Apprehensions | [\<\>](https://github.com/deportationdata/cbp/tree/main/code/apprehensions-code) |
| Encounters | [\<\>](https://github.com/deportationdata/cbp/tree/main/code/encounters-code) |

## Final Dataset Fields

| Canonical Name | Raw Names | Description | Dataset | Data Type |
|---------------|---------------|---------------|---------------|---------------|
| `adult_or_juvenile` | Adult or Juvenile; ADULT OR JUVENILE | Adult or juvenile classification | Apprehensions, Encounters | String |
| `age` | Age; APP AGE; APP Age; APP_AGE; Subject Age | Subject's age | Apprehensions, Encounters | Integer |
| `agent_hash_id` | Agent Hash ID; Arresting Agent Hash# | Hashed arresting-agent identifier | Apprehensions | String |
| `apprehension_datetime` | APP_DT_TIME; APPR_DT_TIME; Arrest DateTime; APPREHENSION_DT; Apprehension Time; Arrest Date; Arrest Time | Apprehension date and time | Apprehensions | Datetime |
| `arrest_at_checkpoint_indicator` | Arrest at Checkpoint (Y/N); Arrest SL Checkpoint Indicator; ARREST AT CHECKPOINT (Y/N); ARREST_AT_CHECKPOINT (Y/N) | Logical indication of whether the arrest occurred at a checkpoint | Apprehensions, Encounters | Boolean |
| `arrest_landmark_desc` | Arrest Landmark Desc | Description of the arrest landmark | Apprehensions | String |
| `arrest_method` | ARREST METHOD; ARREST_METHOD; Arrest Method; Arrest Method Desc | Method of arrest | Apprehensions | String |
| `arrest_sector` | Arrest Sector; SECTOR; Sector; SECTOR_DISTRICT; Sector_District; APPREHENSION SECTOR; Apprehension Sector | Sector of arrest or apprehension | Apprehensions, Encounters | String |
| `arrest_state` | Arrest State; APPREHENSION STATE; Apprehension State | State of arrest or apprehension | Apprehensions, Encounters | String |
| `birth_city` | Birth City; City of Birth | City of birth | Apprehensions | String |
| `birth_country` | Birth Country; Country of Birth; COUNTRY_OF_BIRTH_CD | Country of birth | Apprehensions | String |
| `birth_date` | BIRTH_DATE | Date of birth | Apprehensions | Date |
| `birth_date_redacted` | Generated during cleaning | Logical indication of whether the original birth date contained a redaction marker | Apprehensions | Boolean |
| `birth_state` | Birth State; STATE_OF_BIRTH; State of Birth | State of birth | Apprehensions | String |
| `bookout_sector` | Sector of Bookout; SECTOR OF BOOKED OUT | Sector of bookout | Apprehensions, Encounters | String |
| `border` | Arrest Border; Border; BORDER | Border associated with the arrest or encounter | Apprehensions, Encounters | String |
| `case_file_date` | Case File Date; CASE_FILING_DATE; Case Filing Date; CASE FILING DATE(S); Case Filing Date(s) | Case filing date or dates | Apprehensions | String |
| `case_id` | Case ID; Case ID#; Unique Case Id - we don't provide; Unique Case Identifier | Case identifier | Apprehensions | String |
| `cds_program` | CDS Program; CDS Program Code; CDS PROGRAM(S); CDS Program(s); CDS_PROGRAMS | Program selected under Consequence Delivery System (CDS) | Apprehensions | String |
| `ces_indicator` | CES Criminal Indicator; CES INDICATOR; CES(Y/N) | Logical indication of recorded CES indication | Apprehensions, Encounters | Boolean |
| `charge_code` | Charge Code; CHARGE CODE(S); Charge Code(s); Charge Code / Statue Charge; Charge Code/Statue Code | Recorded charge or statute code or codes | Apprehensions | String |
| `citizenship` | CITIZENSHIP; Citizenship; CITIZENSHIP_CD | Subject's citizenship | Apprehensions, Encounters | String |
| `credible_fear_indicator` | Credible Fear; CREDIBLE_FEAR_IND; Credible Fear Ind; CREDIBLE FEAR INDICATOR; Credible Fear Indicator | Logical indication of recorded credible fear | Apprehensions | Boolean |
| `criminal_conviction_indicator` | CRIMINAL_CONVICTION; Criminal Conviction | Logical indication of a recorded criminal conviction | Apprehensions, Encounters | Boolean |
| `currency_seized_indicator` | Curency Seized During App (Y/N); Currency Seized During App (Y/N) | Logical indication of whether currency was seized during apprehension | Apprehensions | Boolean |
| `currency_seized_value` | Currency Seized During App (\$Value); CURRENCY SEIZ DURING APP; CURRENCY_SEIZ_DURING_APP; Currency Seiz During App (\$Value) | Recorded value of currency seized | Apprehensions, Encounters | Double |
| `currency_seized_value_redacted` | Generated during cleaning | Logical indication of whether the original currency value contained a redaction marker | Encounters | Boolean |
| `dhs_status_cd` | DHS_STATUS_CD; DHS STATUS CODE - LPR | Recorded DHS status code | Apprehensions | String |
| `disposition` | DISPOSITION; Disposition; Subject Disposition Code; Subject Disposition Code (LPR) | Recorded disposition | Apprehensions, Encounters | String |
| `drugs_seized_indicator` | Drugs Seized During App (Y/N); DRUGS SEIZED DURING APPREHENSION (Y/N) | Logical indication of whether drugs were seized during apprehension | Apprehensions, Encounters | Boolean |
| `earliest_encounter_date` | Earliest App Date; EARLIEST APPREHENSION DATE; EARLIEST ENCOUNTER DATE | Earliest recorded encounter or apprehension date | Encounters | Date |
| `earliest_encounter_datetime` | Earliest APP Date Time; Earliest Encounter Date/Time | Earliest recorded encounter or apprehension date and time | Apprehensions | Datetime |
| `encounter_datetime` | APP_DT_TIME; APPR DT TIME; APPR_DT_TIME; ENCOUNTER_DT_TIME; Apprehension Date; Apprehension Time | Encounter date and time | Encounters | Datetime |
| `entry_date` | Entry Date; ENTRY_DT | Date of entry | Apprehensions | Date |
| `entry_status` | Entry Status; Entry Status (includes LPR); STATUS_AT_ENTRY; STATUS_AT_ENTRY_CD; Status at Entry - LPR Status | Recorded status at entry | Apprehensions | String |
| `ero_transfer_dt` | ERO_TRANSFER_DT | Date of transfer to ERO | Apprehensions | String |
| `ethnicity` | Ethnicity; Subject Ethnicity Cd | Subject's ethnicity | Apprehensions | String |
| `event_number` | EVENT_NUMBER; Event Number | Numeric event identifier | Apprehensions | String |
| `final_bookout_date` | Final Bookout; FINAL BOOKOUT DATE; FINAL_BOOKOUT_DATE; Final Bookout Date; Final Bookout Date/Time | Final bookout date | Apprehensions | Date |
| `final_bookout_datetime` | FINAL_BOOKOUT_DATE; FINAL BOOKOUT DATETIME | Final bookout date and time | Encounters | Datetime |
| `first_residence_country` | First Country of Residence; First Country of Residence (Foreign) | First recorded country of residence | Apprehensions | String |
| `fmu_number` | Family Unit Group#; FMU Group Number; FMU_NUMBER; FMU NUMBER(S) | Family-unit group identifier or identifiers | Apprehensions | String |
| `fmu_type` | FAMILY_UNIT_TYPE; Family Unit Type (Demographic) | Family-unit classification | Apprehensions | String |
| `fmua_indication` | FMUA_IND; FMUA INDICATOR; FMUA Indicator |  | Apprehensions | String |
| `gang_affiliation` | GANG AFFILIATION; Gang Affiliation | Recorded gang affiliation | Encounters | String |
| `gang_code` | Gang Code | Recorded gang code | Apprehensions | String |
| `gang_name` | Gang Name | Recorded gang name | Apprehensions | String |
| `gender` | GENDER; Gender; Subject Gender | Subject's gender | Apprehensions, Encounters | String |
| `general_processing_code` | GENERAL_PROCESSING_CODE | Recorded general processing code | Apprehensions | String |
| `immigration_status_code_lpr` | Immigration Status Code (LPR); Subject Immigration Status Code (LPR) | Recorded immigration status code | Apprehensions | String |
| `juvenile_18_indicator` | Juvenile \<18 | Logical indication of whether the subject is under 18 | Apprehensions | Boolean |
| `landmark_withheld_indicator` | Landmark; Landmark Name for Latest Apprehension; Landmark Name for Latest Apprehension Withheld in Full (b)(7)( E); Landmark Name for Latest Apprehension- Withheld in Full (b)(7)( E) | Logical indication of whether landmark information was withheld | Apprehensions | Boolean |
| `language` | LANGUAGE; Language | Subject's language | Apprehensions | String |
| `latitude` | Apprehension Latitude; Arrest Latitude; APPREHENSION LATITUDE; LATITUDE | Latitude of arrest or apprehension | Apprehensions, Encounters | Double |
| `latitude_redacted` | Generated during cleaning | Logical indication of whether the original `latitude` column contained a redaction marker | Apprehensions, Encounters | Boolean |
| `lpr_indicator` | LPR |  | Apprehensions | Boolean |
| `marital_status` | MARITAL STATUS; MARITAL_STATUS; Marital Status; MARITAL_STATUS_CD; Subject Marital Status | Subject's marital status | Apprehensions, Encounters | String |
| `most_recent_encounter_date` | Most Recent Encounter Date; Most Recent App Date; MOST RECENT APPREHENSION DATE; MOST RECENT ENCOUNTER DATE | Most recent recorded encounter or apprehension date | Apprehensions, Encounters | Date |
| `most_recent_encounter_datetime` | Most Recent Encounter Date/Time; Most Recent Prior Encounter Date Time | Most recent recorded encounter date and time | Apprehensions | Datetime |
| `most_recent_prior_entry_datetime` | Most Recent Prior Ent DateTime; Most Recent Prior Entry Date/Time; Most Recent Prior Entry Date; Most Recent Prior Entry Time | Date and time of the most recent prior entry | Apprehensions | Datetime |
| `mpp_indicator` | MPP Indicator; MPP Indicator (Y/N); MPP INDICATOR (Y/N); MPP_INDICATOR (Y/N) | Logical indication of whether Migrant Protection Protocol (MPP) was recorded | Apprehensions, Encounters | Boolean |
| `nationality` | Nationality | Subject's nationality | Apprehensions | String |
| `ncic_charge_code` | NCIC Charge Code; NCIC Charge Code, Defer to DOJ; NCIC Charge Code, owned by DOJ not CBP; NCIC Charge Code(s); NCIC_CHARGE_CODE(S); NCIC Code | Recorded NCIC charge code or codes | Apprehensions | String |
| `ncic_description` | NCIC Desc; NCIC Desc, Defer to DOJ; NCIC Desc, owned by DOJ not CBP; NCIC_DESC(S); NCIC Description | Description associated with the NCIC charge code | Apprehensions | String |
| `number_of_children_and_nationality` | NUMBER_CHILDREN_AND_NATIONALITY; #Children / Nationality; #of Children and Nationality; NUMBER CHILDREN AND NATIONALITY | Number of children and their nationality information | Apprehensions, Encounters | String |
| `number_of_children_in_event` | #of Children in Event | Number of children in the event | Apprehensions | Integer |
| `number_of_people_in_event` | \# of people per Event; #of People per Event; \# of Subjects per Event | Number of people in the event | Apprehensions | Integer |
| `number_of_previous_encounters` | \# of Previous Apprehensions; #of Previous Apprehensions; Number of Previous Apprehensions; NUMBER OF PREVIOUS APPREHENSION; #of Previous Apps; NUMBER OF PREVIOUS ENCOUNTER | Number of previous encounters or apprehensions | Apprehensions, Encounters | Integer |
| `referred_for_prosecution_under_8usc1325_or_8usc1326` | Referred for Prosecution Under 8 USC 1325 or 8 USC 1326; Referred for Prosecution Under 8USC1325 OR 8USC1326; REFFERRED FOR PROSECUTION UNDER 8 USC 1325 OR 8 USC 1326 | Indicates referral for prosecution under 8 USC 1325 or 1326 | Apprehensions, Encounters | String |
| `removal_type` | REMOVAL TYPE; Removal Type; Removal_Type | Recorded type of removal | Apprehensions | String |
| `residence_city` | CITY OF RESIDENCE; CITY_OF_RESIDENCE; City of Residence | City of residence | Encounters | String |
| `residence_city_state` | City/State of Residence | City and state of residence | Apprehensions | String |
| `residence_country` | Country of Residence; COUNTRY_OF_RES_CD; COUNTRY OF RESIDENCE; COUNTRY_OF_RESIDENCE | Country of residence | Apprehensions, Encounters | String |
| `smuggled_cost` | Smuggled Cost; Subject Smuggle Cost; SMUGGLED COST; SMUGGLED_COST | Recorded smuggling cost | Apprehensions, Encounters | Double |
| `source_file` | Generated during part creation | Source filename for the record | Apprehensions, Encounters | String |
| `source_sheet` | Generated during part creation | Source worksheet for the record | Apprehensions, Encounters | String |
| `spp_program` | SPP Program(s); SPP PROGRAM(S) | Recorded SPP program code | Apprehensions, Encounters | String |
| `state` | STATE | N/A, meaning unclear and all values redacted | Apprehensions | String |
| `statute_charge` | Highest Statue Charge; Highest Statute Charge; Statue Charge; Statute Charge; STATUTE_CHARGE(S); Statute Charge(s); STATUTE CHARGE(S) | Recorded statute charge or charges | Apprehensions, Encounters | String |
| `subject_afile_number` | Alien#; Subject AFILE# | Subject's alien number or alien file number | Apprehensions | String |
| `subject_group_classification` | Demographic; Subject Demographic; Subject Demographic (SDI); DEMOGRAPHIC | Subject demographic classification | Apprehensions, Encounters | String |
| `subject_key` | Civ ID; Civ Id(Subject Key); Civ Id(Subject Key) Unique Identifier; SUBJECT_ID; SUBJECT_KEY | Subject identifier | Apprehensions | String |
| `subject_prosecution_indicator` | Prosecution Indicator; REFERRED PROSECUTION; Referred Prosecution; Subject Prosecution Indicator | Logical indication of recorded prosecution or prosecution-referral | Apprehensions | Boolean |
| `suspected_gang_member_indicator` | SUSPECTED_GANG_MEMBER | Logical indication of recorded suspected gang membership | Apprehensions | Boolean |
| `suspected_gang_member_indicator_redacted` | Generated during cleaning | Logical indication of whether the original gang-membership indicator contained a redaction marker | Apprehensions | Boolean |
| `time_in_us` | Subject Time In US; Time in US; TIME IN US; TIME_IN_US; TIME_IN_US_CD | Recorded time in the United States | Apprehensions, Encounters | String |
| `transfer_to` | TRANSFER_TO | Recorded transfer destination | Apprehensions | String |
| `transfer_to_group` | ERO_TRANSFER; Transfer To ERO; TRANSFER_TO_GROUP; Transferred To Group; Transferred to Group; Transferred to Group / Removal Type (ERO); TRANSFERRED TO GROUP; TRANSFERRED_TO_GROUP | Recorded group receiving the transfer | Apprehensions, Encounters | String |
| `type_of_drugs_seized` | Type of Drugs Seized During App; Type of Drugs Seized during App; TYPE OF DRUGS SEIZED DURING APPREHENSION | Type of drugs seized during apprehension | Apprehensions, Encounters | String |
| `unaccompanied_child_indicator` | UAC_IND; UC INDICATOR; UC Indicator; UNACCOMPANIED CHILD; UNACCOMPANIED_CHILD; UC INDICATOR (Y/N) | Indicates unaccompanied-child status | Apprehensions, Encounters | Boolean |
| `unique_person_id` | Unique Person Id - we don't provide; Unique Person Identifier | Unique person identifier | Apprehensions | String |

The final script in each pipeline selects columns based on usefulness and percent missing. Apprehensions dataset retains `apprehension_datetime`, `entry_date`, `final_bookout_date`, `arrest_sector`, `arrest_method`, `age`, `gender`, `citizenship`, `marital_status`, `number_of_children_and_nationality`, `fmua_indication`, `unaccompanied_child_indicator`, `entry_status`, `credible_fear_indicator`, `cds_program`, `prosecution_indicator`, `statute_charge`, `charge_code`, `disposition`, `removal_type`, `source_file`, and `source_sheet.`
The final Encounters dataset retains `encounter_datetime`, `most_recent_encounter_date`, `earliest_encounter_date`, `number_of_previous_encounters`, `final_bookout_datetime`, `border`, `arrest_sector`, `bookout_sector`, `arrest_state`, `arrest_at_checkpoint_indicator`, `age`, `adult_or_juvenile`, `gender`, `citizenship`, `residence_city`, `residence_country`, `marital_status`, `subject_group_classification`, `number_of_children_and_nationality`, `time_in_us`, `ces_indicator`, `mpp_indicator`, `transfer_to_group`, `drugs_seized_indicator`, `statute_charge`, `disposition`, `referred_for_prosecution_under_8usc1325_or_8usc1326`, `source_file`, and `source_sheet.`

## Warnings and Limitations

Below are some limitations to consider when accessing this data:

-   **USBP vs. OFO Encounters**: Our encounters dataset contains only encounters recorded by USBP, including Title 8 apprehensions and Title 42 expulsions. It excludes Title 8 inadmissibles recorded by OFO. Aggregated data on all encounters can be found on [CBP’s website](https://www.cbp.gov/document/stats/nationwide-encounters). Individual-level data is available only for USBP encounters.

-   **Column harmonization**: CBP lacks clear documentation about all of the headers included in our datasets. Our codebook indicates where intended meanings and methods of measurement were not apparent. Identical headers may not have had the same meaning across different datasets. Columns were merged to the best of our ability but still may contain errors.

-   **Manual function prompting:** Several scripts contain binary functions that must be manually set to `TRUE` or `FALSE` when updating data. Please visit the `README.md` for instructions on how to correctly run the scripts.

-   **Lack of subject identifiers:** CBP redacted all subject identification columns, making it impossible to identify which rows contained encounters with the same individual. When using this data, keep in mind that each row in both datasets refers to an encounter rather than an individual.

-   **Missing values:** Missing values were not recorded in a standard fashion across datasets. Where some included "NA" values, others left cells blank. Many columns also contain redacted values. The differences in recording methods and missing information indications should be noted when interpreting this data.

-   **Redaction codes:** CBP redaction codes used in released documents refer to standard Freedom of Information Act (FOIA) statutory exemptions. Redaction codes that can be found in the data include:

    -   **Exemption (b)(6):** Protects information that would constitute an unwarranted invasion of personal privacy of individuals involved.
    -   **Exemption (b)(7)(C):** Protects information that would constitute an unwarranted invasion of the personal privacy of a third party/parties (in some instances by revealing an investigative interest in them).
    -   **Exemption (b)(7)(E):** Protects information that would disclose techniques and procedures for law enforcement investigations or prosecutions.

    More information can be found at [hhs.gov](https://www.hhs.gov/foia/exemptions-and-exclusions/index.html).

-   **Excluded files:** If entire datasets were determined to be duplicates of each other, one was excluded from the final dataset. We have one instance of this in apprehensions.

    -   **Apprehensions:** The Quarter 4 2024 apprehensions dataset (**`usbp_nationwide_apprehension_q4_fy_2024.xlsx)`** was deleted and not merged. This file was concluded to be an erroneous duplicate of the Quarter 3 2024 apprehensions dataset (**`usbp_nationwide_apprehension_q3_fy_2024.xlsx`**).

-   **Overlapping dates:** Several raw apprehension datasets were found to record overlapping periods of time. In these instances, we retained broader datasets over more granular ones to prioritize consistency. `cbp/data/<dataset>/processed/<dataset>.stacked.parquet` contains all non-duplicate datasets.

-   **Link permanence:** Files are identified by their URLs published on CBP’s website. If CBP replaces the contents of an existing URL the pipeline will not automatically detect this revision. We are currently updating the process to avoid this issue.

-   **Redacted values:** At times, redacted codes were present in columns whose data types were cleaned to non-character columns. In this case, redacted codes were converted to NA values. If this occurred, a companion flag column was created to indicate whether the NA was previously a redacted value.

## Citation

BibTeX citation: @dataset{blair2026, author = {Blair, Graeme and Horowitz, Simone}, title = {CBP Data Codebook}, date = {2026}, url = {<https://github.com/deportationdata/cbp>}, langid = {en} }

For attribution, please cite this work as: Blair, Graeme, and Simone Horowitz. 2026. “CBP Data Codebook.”
