---
title: "cbp-weekly-counts"
output: pdf
date: "2026-08-13"
---

```{r Setup}
# packages
library(tidyverse)
library(arrow)
library(lubridate)
library(ggrepel)
library(here)
```

## Encounters Over Time

```{r ENCOUNTERS}
# paths
dataset_dir <- here("data", "encounters")
processed_dir <- file.path(dataset_dir, "processed")
metadata_dir <- file.path(dataset_dir, "metadata")

encounters_final_path <- file.path(
  processed_dir,
  "encounters-final.parquet"
)

parts_metadata_path <- file.path(
  metadata_dir,
  "parts-metadata.parquet"
)

parts_metadata <- read_parquet(
  parts_metadata_path
)

# part lookup 
part_lookup <- parts_metadata |>
  transmute(
    source_file,
    part_number = str_sub(
      part_file,
      start = 1,
      end = 4
    )
  ) |>
  distinct()

# select date data
weekly_encounters <- encounters_final_path |>
  open_dataset() |>
  select(
    encounter_datetime,
    source_file,
    source_sheet
  ) |>
  mutate(
    event_date = as.Date(encounter_datetime),
    week_start = floor_date(
      event_date,
      unit = "week",
      week_start = 1
    )
  ) |>
  filter(
    !is.na(week_start)
  ) |>
  group_by(
    source_file,
    source_sheet,
    week_start
  ) |>
  summarize(
    encounter_count = n(),
    .groups = "drop"
  ) |>
  collect() |>
  left_join(
  part_lookup,
  by = "source_file"
) |>
  arrange(
    part_number,
    week_start
  )

# plot
weekly_encounters_plot <- ggplot(
  weekly_encounters,
  aes(
    x = week_start,
    y = encounter_count,
    group = part_number,
    color = part_number
  )
) +
  geom_line(
    linewidth = 0.5
  ) +
  scale_x_date(
    date_breaks = "1 year",
    date_labels = "%Y"
  ) +
  labs(
    title = "Weekly USBP Encounter by Source Part",
    x = NULL,
    y = "Encounter Count",
    caption = "Source: U.S. Customs and Border Protection"
  ) +
  theme_minimal()

weekly_encounters_plot

# save plot
ggsave(
  here("analysis", "weekly-apprehensions-plot.pdf"),
  plot = weekly_encounters_plot,
  width = 24,
  height = 14,
  units = "in",
  limitsize = FALSE
)

```

## Apprehensions Over Time

```{r APPREHENSIONS }
# paths
dataset_dir <- here("data", "apprehensions")
processed_dir <- file.path(dataset_dir, "processed")
metadata_dir <- file.path(dataset_dir, "metadata")

apprehensions_final_path <- file.path(
  processed_dir,
  "apprehensions-final.parquet"
)

parts_metadata_path <- file.path(
  metadata_dir,
  "parts-metadata.parquet"
)

parts_metadata <- read_parquet(
  parts_metadata_path
)

# part lookup 
part_lookup <- parts_metadata |>
  transmute(
    source_file,
    part_number = str_sub(
      part_file,
      start = 1,
      end = 4
    )
  ) |>
  distinct()


# select date data
weekly_apprehensions <- apprehensions_final_path |>
  open_dataset() |>
  select(
    apprehension_datetime,
    source_file,
    source_sheet
  ) |>
  mutate(
    event_date = as.Date(apprehension_datetime),
    week_start = floor_date(
      event_date,
      unit = "week",
      week_start = 1
    )
  ) |>
  filter(
    !is.na(week_start)
  ) |>
  group_by(
    source_file,
    source_sheet,
    week_start
  ) |>
  summarize(
    apprehension_count = n(),
    .groups = "drop"
  ) |>
  collect() |>
  left_join(
  part_lookup,
  by = "source_file"
) |>
  arrange(
    part_number,
    week_start
  )


# plot (2024)
line_labels_2024 <- weekly_apprehensions |>
  filter(
    week_start >= as.Date("2024-01-01")
  ) |>
  group_by(
    part_number
  ) |> 
  slice_max(
    week_start,
    n = 1,
    with_ties = FALSE
) |>
  ungroup()

weekly_apprehensions_plot_2024 <- ggplot(
  weekly_apprehensions,
  aes(
    x = week_start,
    y = apprehension_count,
    group = part_number,
    color = part_number
  )
) +
  geom_line(
    linewidth = 0.5
  ) +
  coord_cartesian(xlim = as.Date(c("2024-01-01", NA))) +
  scale_x_date(
    date_breaks = "1 year",
    date_labels = "%Y"
  ) +
  labs(
    title = "Weekly USBP Apprehensions by Source Part",
    x = NULL,
    y = "Apprehension Count",
    caption = "Source: U.S. Customs and Border Protection"
  ) +
   geom_text_repel(
    data = line_labels_2024,
    aes(label = part_number)) +
  theme_minimal()

weekly_apprehensions_plot_2024


# plot
weekly_apprehensions_plot <- ggplot(
  weekly_apprehensions,
  aes(
    x = week_start,
    y = apprehension_count,
    group = part_number,
    color = part_number
  )
) +
  geom_line(
    linewidth = 0.5
  ) +
  scale_x_date(
    date_breaks = "1 year",
    date_labels = "%Y"
  ) +
  labs(
    title = "Weekly USBP Apprehensions by Source Part",
    x = NULL,
    y = "Apprehension Count",
    caption = "Source: U.S. Customs and Border Protection"
  ) +
  theme_minimal()

weekly_apprehensions_plot

# save plot
ggsave(
  here("analysis/weekly-apprehensions-plot.pdf"),
  plot = weekly_apprehensions_plot,
  width = 24,
  height = 14,
  units = "in",
  limitsize = FALSE
)

ggsave(
  here("analysis/weekly-apprehensions-plot-2024.pdf"),
  plot = weekly_apprehensions_plot_2024,
  width = 24,
  height = 14,
  units = "in",
  limitsize = FALSE
)
```


## Encounters and Apprehensions 
```{r SUPERIMPOSED}
# paths
encounters_dir <- here("data", "encounters")
apprehensions_dir <- here("data", "apprehensions")

encounters_processed_dir <- file.path(encounters_dir, "processed")
apprehensions_processed_dir <- file.path(apprehensions_dir, "processed")

encounters_final_path <- file.path(
  encounters_processed_dir,
  "encounters-final.parquet"
)
apprehensions_final_path <- file.path(
  apprehensions_processed_dir,
  "apprehensions-final.parquet"
)


# count apprehensions by date
apprehensions_daily <- open_dataset(apprehensions_final_path) |>
  mutate(
    event_date = as.Date(apprehension_datetime)
  ) |>
  filter(
    !is.na(event_date)
  ) |>
  group_by(event_date) |>
  summarize(
    count = n(),
    .groups = "drop"
  ) |>
  collect() |>
  mutate(
    dataset = "Apprehensions"
  )

# count encounters by date
encounters_daily <- open_dataset(encounters_final_path) |>
  mutate(
    event_date = as.Date(encounter_datetime)
  ) |>
  filter(
    !is.na(event_date)
  ) |>
  group_by(event_date) |>
  summarize(
    count = n(),
    .groups = "drop"
  ) |>
  collect() |>
  mutate(
    dataset = "Encounters"
  )

# combine weekly counts
weekly_comparison <- bind_rows(
  apprehensions_daily,
  encounters_daily
) |>
  mutate(
    week_start = floor_date(
      event_date,
      unit = "week",
      week_start = 1
    )
  ) |>
  group_by(
    dataset,
    week_start
  ) |>
  summarize(
    count = sum(count),
    .groups = "drop"
  ) |>
  arrange(
    dataset,
    week_start
  )

# plot
weekly_comparison_plot <- ggplot(
  weekly_comparison,
  aes(
    x = week_start,
    y = count,
    color = dataset,
    linetype = dataset
  )
) +
  geom_line(
    linewidth = 0.6,
    alpha = 0.8
  ) +
  scale_color_manual(
    values = c(
      "Apprehensions" = "#0072B2",
      "Encounters" = "#D55E00"
    )
  ) +
  scale_x_date(
    date_breaks = "1 year",
    date_labels = "%Y"
  ) +
  scale_y_continuous(
    labels = scales::label_comma()
  ) +
  labs(
    title = "Weekly USBP Apprehensions and Encounters",
    x = NULL,
    y = "Weekly record count",
    color = NULL,
    linetype = NULL,
    caption = "Source: U.S. Customs and Border Protection."
  ) +
  annotate(
    "segment",
    x = as.Date("2020-03-21"),
    xend = as.Date("2023-05-11"),
    y = max(weekly_comparison$count, na.rm = TRUE) * 1.08,
    yend = max(weekly_comparison$count, na.rm = TRUE) * 1.08,
    linewidth = 0.5
  ) +
  annotate(
    "text",
    x = as.Date("2021-10-15"),
    y = max(weekly_comparison$count, na.rm = TRUE) * 1.13,
    label = "Title 42 in effect",
    size = 2.5
  ) +
  annotate(
    "segment",
    x = as.Date(c("2020-03-21", "2023-05-11")),
    xend = as.Date(c("2020-03-21", "2023-05-11")),
    y = max(weekly_comparison$count, na.rm = TRUE) * 1.06,
    yend = max(weekly_comparison$count, na.rm = TRUE) * 1.10,
    linewidth = 0.5
  ) +
  theme_minimal() +
  theme(
    legend.position = "bottom"
  )

weekly_comparison_plot


ggsave(
  here("analysis/weekly-encounters-and-apprehensions.png"),
  plot = weekly_comparison_plot,
  width = 24,
  height = 14,
  units = "in",
  limitsize = FALSE
)
```

## Inadmissibles Over Time

```{r INADMISSIBLES}
# paths
dataset_dir <- here("data", "apprehensions")
processed_dir <- file.path(dataset_dir, "processed")
metadata_dir <- file.path(dataset_dir, "metadata")

inadmissibles_final_path <- file.path(
  processed_dir,
  "inadmissibles-final.parquet"
)

parts_metadata_path <- file.path(
  metadata_dir,
  "parts-metadata.parquet"
)

parts_metadata <- read_parquet(
  parts_metadata_path
)

# part lookup 
part_lookup <- parts_metadata |>
  transmute(
    source_file,
    part_number = str_sub(
      part_file,
      start = 1,
      end = 4
    )
  ) |>
  distinct()


# select date data
weekly_inadmissibles <- inadmissibles_final_path |>
  open_dataset() |>
  select(
    event_created_datetime,
    source_file,
    source_sheet
  ) |>
  mutate(
    event_date = as.Date(
      event_created_datetime
    ),
    week_start = floor_date(
      event_date,
      unit = "week",
      week_start = 1
    )
  ) |>
  filter(
    !is.na(week_start)
  ) |>
  group_by(
    source_file,
    source_sheet,
    week_start
  ) |>
  summarize(
    inadmissible_count = n(),
    .groups = "drop"
  ) |>
  collect() |>
  left_join(
  part_lookup,
  by = "source_file"
) |>
  arrange(
    part_number,
    week_start
  )

# plot 
weekly_inadmissibles_plot <- ggplot(
  weekly_inadmissibles,
  aes(
    x = week_start,
    y = inadmissible_count,
    group = part_number,
    color = part_number
  )
) +
  geom_line(
    linewidth = 0.5
  ) +
  scale_x_date(
    date_breaks = "1 year",
    date_labels = "%Y"
  ) +
  labs(
    title = "Weekly OFO Inadmissibles by Source Part",
    x = NULL,
    y = "Inadmissible Count",
    caption = "Source: U.S. Customs and Border Protection"
  ) +
  theme_minimal()

weekly_inadmissibles_plot

# plot (2024)
line_labels_2024 <- weekly_inadmissibles |>
  filter(
    week_start >= as.Date("2024-01-01")
  ) |>
  group_by(
    part_number
  ) |> 
  slice_max(
    week_start,
    n = 1,
    with_ties = FALSE
) |>
  ungroup()

weekly_inadmissibles_plot_2024 <- ggplot(
  weekly_inadmissibles,
  aes(
    x = week_start,
    y = inadmissible_count,
    group = part_number,
    color = part_number
  )
) +
  geom_line(
    linewidth = 0.5
  ) +
  scale_x_date(
    date_breaks = "1 year",
    date_labels = "%Y"
  ) +
  coord_cartesian(xlim = as.Date(c("2024-01-01", NA))) +
  labs(
    title = "Weekly OFO Inadmissibles by Source Part",
    x = NULL,
    y = "Inadmissible Count",
    caption = "Source: U.S. Customs and Border Protection"
  ) +
  geom_text_repel(
    data = line_labels_2024,
    aes(label = part_number)
  ) +
  theme_minimal()

weekly_inadmissibles_plot_2024

# save plot
ggsave(
  "analysis/weekly-inadmissibles-plot.pdf",
  plot = weekly_inadmissibles_plot,
  width = 24,
  height = 14,
  units = "in",
  limitsize = FALSE
)

ggsave(
  "analysis/weekly-inadmissibles-plot-2024.pdf",
  plot = weekly_inadmissibles_plot_2024,
  width = 24,
  height = 14,
  units = "in",
  limitsize = FALSE
)
```

